kind: "List"
apiVersion: "v1"
items:
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "gogs-data"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "10Gi"
    volumeName: "fabric8-gogs-data"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-mvn-local-repo"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "10Gi"
    volumeName: "fabric8-jenkins-mvn-local-repo"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-jobs"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "5Gi"
    volumeName: "fabric8-jenkins-jobs"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "jenkins-workspace"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "5Gi"
    volumeName: "fabric8-jenkins-workspace"

- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
    name: "nexus-storage"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "18Gi"
    volumeName: "fabric8-nexus-storage"
##########  pv
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabric8-nexus-storage
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 20Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /data/nfs/volumes/db
      server: 172.16.5.58

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabric8-gogs-data
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 50Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /data/nfs/volumes/db
      server: 172.16.5.58

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabric8-jenkins-mvn-local-repo
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /data/nfs/volumes/db
      server: 172.16.5.58

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabric8-jenkins-jobs
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /data/nfs/volumes/db
      server: 172.16.5.58

- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: fabric8-jenkins-workspace
    labels:
      provider: "fabric8"
      group: "io.fabric8.devops.apps"
  spec:
    capacity:
      storage: 10Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /data/nfs/volumes/db
      server: 172.16.5.58
