apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: d75bd35f037447e540543b2f9ad0bb0843ac77ba
    fabric8.io/git-branch: release-v1.0.23
    fabric8.io/metrics-path: >-
      dashboard/file/kubernetes-pods.json/?var-project=hystrix-dashboard&var-version=1.0.23
    fabric8.io/build-id: '1'
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/d75bd35f037447e540543b2f9ad0bb0843ac77ba
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/1'
  labels:
    project: hystrix-dashboard
    provider: fabric8
    version: 1.0.23
    group: io.fabric8.kubeflix
  name: hystrix-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      project: hystrix-dashboard
      provider: fabric8
      group: io.fabric8.kubeflix
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: d75bd35f037447e540543b2f9ad0bb0843ac77ba
        fabric8.io/metrics-path: >-
          dashboard/file/kubernetes-pods.json/?var-project=hystrix-dashboard&var-version=1.0.23
        fabric8.io/build-id: '1'
        fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/1'
        fabric8.io/git-branch: release-v1.0.23
        fabric8.io/git-url: >-
          http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/d75bd35f037447e540543b2f9ad0bb0843ac77ba
      labels:
        project: hystrix-dashboard
        provider: fabric8
        version: 1.0.23
        group: io.fabric8.kubeflix
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 'fabric8/hystrix-dashboard:1.0.23'
          imagePullPolicy: IfNotPresent
          name: hystrix-dashboard
          ports:
            - containerPort: 8080
              name: http
      serviceAccountName: ribbon
endGroup: false
newGroup: true

