apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    provider: fabric8
    project: hystrix-dashboard
    version: 1.0.23
    group: io.fabric8.kubeflix
  name: ribbon
  annotations: {}
endGroup: true
newGroup: true
