apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: d75bd35f037447e540543b2f9ad0bb0843ac77ba
    fabric8.io/git-branch: release-v1.0.23
    fabric8.io/build-id: '1'
    fabric8.io/git-url: >-
      http://gogs.ux.fabric8.io/gogsadmin/oss-parent/commit/d75bd35f037447e540543b2f9ad0bb0843ac77ba
    fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/1'
  labels:
    project: hystrix-dashboard
    provider: fabric8
    version: 1.0.23
    group: io.fabric8.kubeflix
  name: hystrix-dashboard
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    project: hystrix-dashboard
    provider: fabric8
    group: io.fabric8.kubeflix
  type: LoadBalancer
endGroup: true
newGroup: true
