apiVersion: v1
kind: Service
metadata:
  annotations:
    servicepath: /turbine.stream
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: release-v1.0.26
  labels:
    project: turbine-server
    provider: fabric8
    version: 1.0.26
    group: io.fabric8.kubeflix
  name: turbine-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    project: turbine-server
    provider: fabric8
    group: io.fabric8.kubeflix
  type: LoadBalancer
