apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/metrics-path: >-
      dashboard/file/kubernetes-pods.json/?var-project=turbine-server&var-version=1.0.26
    fabric8.io/build-id: '1'
    fabric8.io/iconUrl: img/icons/spring-boot.svg
    fabric8.io/git-branch: release-v1.0.26
  labels:
    project: turbine-server
    provider: fabric8
    version: 1.0.26
    group: io.fabric8.kubeflix
  name: turbine-server
spec:
  replicas: 1
  selector:
    matchLabels:
      project: turbine-server
      provider: fabric8
      group: io.fabric8.kubeflix
  template:
    metadata:
      annotations:
        fabric8.io/metrics-path: >-
          dashboard/file/kubernetes-pods.json/?var-project=turbine-server&var-version=1.0.26
        fabric8.io/build-id: '1'
        fabric8.io/build-url: 'http://jenkins.ux.fabric8.io/job/oss-parent/1'
        fabric8.io/iconUrl: img/icons/spring-boot.svg
        fabric8.io/git-branch: release-v1.0.26
      labels:
        project: turbine-server
        provider: fabric8
        version: 1.0.26
        group: io.fabric8.kubeflix
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: 'fabric8/turbine-server:1.0.26'
          imagePullPolicy: IfNotPresent
          name: turbine-server
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8778
              name: jolokia
      serviceAccountName: turbine
