apiVersion: v1
kind: DeploymentConfig
metadata:
  name: mysql
  namespace: fabric8-staging
  labels:
    app: mysql-persistent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
    spec:
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-storage
      containers:
        - name: mysql
          image: 'mysql:5.7'
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: '@vpclubdev'
            - name: MYSQL_DATABASE
              value: mysql
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                  -D $MYSQL_DATABASE -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}

