apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: hazelcast
  name: hazelcast-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast-center
    spec:
      containers:
      - name: hazelcast-center
        image: hazelcast/management-center:latest
        ports:
        - containerPort: 8080
