apiVersion: v1
kind: Service
metadata:
  name: hazelcast-center
  labels:
    app: hazelcast-center
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: hazelcast-center

