#!/bin/bash
source ../log.sh
source ../clap.sh

if [ "" == "$registry" ]; then
  log 'please specify registry=yourregistry, e.g. ./migrate-logging-image registry=172.16.5.60:5000 version=v1.4.0-alpha.1'
  exit 1
fi

if [ "" == "$versison" ]; then
  log 'please specify version=yourversion, e.g. ./migrate-logging-image registry=172.16.5.60:5000 version=v1.4.0-alpha.1'
  exit 1
fi

./migrate-image-local "openshift/origin-logging-deployment:$version openshift/origin-logging-curator:$version openshift/origin-logging-elasticsearch:$version openshift/origin-logging-kibana:$version openshift/origin-logging-auth-proxy:$version" $registry

exit 0

